/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC20Extended,
  IERC20ExtendedInterface,
} from "../IERC20Extended";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC20Extended__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20ExtendedInterface {
    return new utils.Interface(_abi) as IERC20ExtendedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20Extended {
    return new Contract(address, _abi, signerOrProvider) as IERC20Extended;
  }
}
