/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MurkyBaseInterface extends ethers.utils.Interface {
  functions: {
    "getProof(bytes32[],uint256)": FunctionFragment;
    "getRoot(bytes32[])": FunctionFragment;
    "hashLeafPairs(bytes32,bytes32)": FunctionFragment;
    "log2ceil(uint256)": FunctionFragment;
    "log2ceilBitMagic(uint256)": FunctionFragment;
    "verifyProof(bytes32,bytes32[],bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getProof",
    values: [BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoot",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hashLeafPairs",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "log2ceil",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "log2ceilBitMagic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashLeafPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "log2ceil", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "log2ceilBitMagic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;

  events: {};
}

export class MurkyBase extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MurkyBaseInterface;

  functions: {
    getProof(
      data: BytesLike[],
      node: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getRoot(data: BytesLike[], overrides?: CallOverrides): Promise<[string]>;

    hashLeafPairs(
      left: BytesLike,
      right: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { _hash: string }>;

    log2ceil(x: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    log2ceilBitMagic(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verifyProof(
      root: BytesLike,
      proof: BytesLike[],
      valueToProve: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getProof(
    data: BytesLike[],
    node: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRoot(data: BytesLike[], overrides?: CallOverrides): Promise<string>;

  hashLeafPairs(
    left: BytesLike,
    right: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  log2ceil(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  log2ceilBitMagic(
    x: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  verifyProof(
    root: BytesLike,
    proof: BytesLike[],
    valueToProve: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getProof(
      data: BytesLike[],
      node: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRoot(data: BytesLike[], overrides?: CallOverrides): Promise<string>;

    hashLeafPairs(
      left: BytesLike,
      right: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    log2ceil(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    log2ceilBitMagic(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyProof(
      root: BytesLike,
      proof: BytesLike[],
      valueToProve: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getProof(
      data: BytesLike[],
      node: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoot(data: BytesLike[], overrides?: CallOverrides): Promise<BigNumber>;

    hashLeafPairs(
      left: BytesLike,
      right: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    log2ceil(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    log2ceilBitMagic(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyProof(
      root: BytesLike,
      proof: BytesLike[],
      valueToProve: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getProof(
      data: BytesLike[],
      node: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoot(
      data: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashLeafPairs(
      left: BytesLike,
      right: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    log2ceil(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    log2ceilBitMagic(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyProof(
      root: BytesLike,
      proof: BytesLike[],
      valueToProve: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
